// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (user_id, telegram_update_id, chat_id, raw_text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (telegram_update_id) DO NOTHING
RETURNING id
`

type InsertMessageParams struct {
	UserID           pgtype.UUID
	TelegramUpdateID int64
	ChatID           int64
	RawText          string
}

// No conflito de telegram_update_id nenhuma linha é devolvida (pgx.ErrNoRows
// no :one): é assim que o chamador sabe que o update já estava gravado.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.UserID,
		arg.TelegramUpdateID,
		arg.ChatID,
		arg.RawText,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
