// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (telegram_user_id)
VALUES ($1)
ON CONFLICT (telegram_user_id) DO UPDATE SET telegram_user_id = EXCLUDED.telegram_user_id
RETURNING id
`

// O DO UPDATE sem efeito existe só para o RETURNING devolver o id também no
// conflito (com DO NOTHING o Postgres não devolve a linha existente).
func (q *Queries) UpsertUser(ctx context.Context, telegramUserID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUser, telegramUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
